using System.Dynamic;
using System.Reflection.Metadata;
using Newtonsoft.Json;

namespace ShrimpleCmd
{
    public class Settings
    {
        public bool firstTime { set; get; }
        public bool debugMode { set; get; }
        public string internalCommandPrefix { set; get; }
        public bool enforcePrefix { set; get; }

        public bool unicodeConversion { set; get; }
        public int MaxHistoryLength { set; get; }
        public enum HistoryUp
        {
            UpArrow = ConsoleKey.UpArrow,
            DownArrow = ConsoleKey.DownArrow,
            Backspace = ConsoleKey.Backspace,
            Tab = ConsoleKey.Tab,
            Clear = ConsoleKey.Clear,
            Enter = ConsoleKey.Enter,
            Pause = ConsoleKey.Pause,
            Escape = ConsoleKey.Escape,
            Spacebar = ConsoleKey.Spacebar,
            PageUp = ConsoleKey.PageUp,
            PageDown = ConsoleKey.PageDown,
            End = ConsoleKey.End,
            Home = ConsoleKey.Home,
            LeftArrow = ConsoleKey.LeftArrow,
            RightArrow = ConsoleKey.RightArrow,
            Select = ConsoleKey.Select,
            Print = ConsoleKey.Print,
            Execute = ConsoleKey.Execute,
            PrintScreen = ConsoleKey.PrintScreen,
            Insert = ConsoleKey.Insert,
            Delete = ConsoleKey.Delete,
            Help = ConsoleKey.Help,
            D0 = ConsoleKey.D0,
            D1 = ConsoleKey.D1,
            D2 = ConsoleKey.D2,
            D3 = ConsoleKey.D3,
            D4 = ConsoleKey.D4,
            D5 = ConsoleKey.D5,
            D6 = ConsoleKey.D6,
            D7 = ConsoleKey.D7,
            D8 = ConsoleKey.D8,
            D9 = ConsoleKey.D9,
            A = ConsoleKey.A,
            B = ConsoleKey.B,
            C = ConsoleKey.C,
            D = ConsoleKey.D,
            E = ConsoleKey.E,
            F = ConsoleKey.F,
            G = ConsoleKey.G,
            H = ConsoleKey.H,
            I = ConsoleKey.I,
            J = ConsoleKey.J,
            K = ConsoleKey.K,
            L = ConsoleKey.L,
            M = ConsoleKey.M,
            N = ConsoleKey.N,
            O = ConsoleKey.O,
            P = ConsoleKey.P,
            Q = ConsoleKey.Q,
            R = ConsoleKey.R,
            S = ConsoleKey.S,
            T = ConsoleKey.T,
            U = ConsoleKey.U,
            V = ConsoleKey.V,
            W = ConsoleKey.W,
            X = ConsoleKey.X,
            Y = ConsoleKey.Y,
            Z = ConsoleKey.Z,
            LeftWindows = ConsoleKey.LeftWindows,
            RightWindows = ConsoleKey.RightWindows,
            Applications = ConsoleKey.Applications,
            Sleep = ConsoleKey.Sleep,
            NumPad0 = ConsoleKey.NumPad0,
            NumPad1 = ConsoleKey.NumPad1,
            NumPad2 = ConsoleKey.NumPad2,
            NumPad3 = ConsoleKey.NumPad3,
            NumPad4 = ConsoleKey.NumPad4,
            NumPad5 = ConsoleKey.NumPad5,
            NumPad6 = ConsoleKey.NumPad6,
            NumPad7 = ConsoleKey.NumPad7,
            NumPad8 = ConsoleKey.NumPad8,
            NumPad9 = ConsoleKey.NumPad9,
            Multiply = ConsoleKey.Multiply,
            Add = ConsoleKey.Add,
            Separator = ConsoleKey.Separator,
            Subtract = ConsoleKey.Subtract,
            Decimal = ConsoleKey.Decimal,
            Divide = ConsoleKey.Divide,
            F1 = ConsoleKey.F1,
            F2 = ConsoleKey.F2,
            F3 = ConsoleKey.F3,
            F4 = ConsoleKey.F4,
            F5 = ConsoleKey.F5,
            F6 = ConsoleKey.F6,
            F7 = ConsoleKey.F7,
            F8 = ConsoleKey.F8,
            F9 = ConsoleKey.F9,
            F10 = ConsoleKey.F10,
            F11 = ConsoleKey.F11,
            F12 = ConsoleKey.F12,
            F13 = ConsoleKey.F13,
            F14 = ConsoleKey.F14,
            F15 = ConsoleKey.F15,
            F16 = ConsoleKey.F16,
            F17 = ConsoleKey.F17,
            F18 = ConsoleKey.F18,
            F19 = ConsoleKey.F19,
            F20 = ConsoleKey.F20,
            F21 = ConsoleKey.F21,
            F22 = ConsoleKey.F22,
            F23 = ConsoleKey.F23,
            F24 = ConsoleKey.F24,
            BrowserBack = ConsoleKey.BrowserBack,
            BrowserForward = ConsoleKey.BrowserForward,
            BrowserRefresh = ConsoleKey.BrowserRefresh,
            BrowserStop = ConsoleKey.BrowserStop,
            BrowserSearch = ConsoleKey.BrowserSearch,
            BrowserFavorites = ConsoleKey.BrowserFavorites,
            BrowserHome = ConsoleKey.BrowserHome,
            VolumeMute = ConsoleKey.VolumeMute,
            VolumeDown = ConsoleKey.VolumeDown,
            VolumeUp = ConsoleKey.VolumeUp,
            MediaNext = ConsoleKey.MediaNext,
            MediaPrevious = ConsoleKey.MediaPrevious,
            MediaStop = ConsoleKey.MediaStop,
            MediaPlay = ConsoleKey.MediaPlay,
            LaunchMail = ConsoleKey.LaunchMail,
            LaunchMediaSelect = ConsoleKey.LaunchMediaSelect,
            LaunchApp1 = ConsoleKey.LaunchApp1,
            LaunchApp2 = ConsoleKey.LaunchApp2,
            Oem1 = ConsoleKey.Oem1,
            OemPlus = ConsoleKey.OemPlus,
            OemComma = ConsoleKey.OemComma,
            OemMinus = ConsoleKey.OemMinus,
            OemPeriod = ConsoleKey.OemPeriod,
            Oem2 = ConsoleKey.Oem2,
            Oem3 = ConsoleKey.Oem3,
            Oem4 = ConsoleKey.Oem4,
            Oem5 = ConsoleKey.Oem5,
            Oem6 = ConsoleKey.Oem6,
            Oem7 = ConsoleKey.Oem7,
            Oem8 = ConsoleKey.Oem8,
            Oem102 = ConsoleKey.Oem102,
            Process = ConsoleKey.Process,
            Packet = ConsoleKey.Packet,
            Attention = ConsoleKey.Attention,
            CrSel = ConsoleKey.CrSel,
            ExSel = ConsoleKey.ExSel,
            EraseEndOfFile = ConsoleKey.EraseEndOfFile,
            Play = ConsoleKey.Play,
            Zoom = ConsoleKey.Zoom,
            NoName = ConsoleKey.NoName,
            Pa1 = ConsoleKey.Pa1,
            OemClear = ConsoleKey.OemClear
        }
        public enum HistoryDown
        {
            UpArrow = ConsoleKey.UpArrow,
            DownArrow = ConsoleKey.DownArrow,
            Backspace = ConsoleKey.Backspace,
            Tab = ConsoleKey.Tab,
            Clear = ConsoleKey.Clear,
            Enter = ConsoleKey.Enter,
            Pause = ConsoleKey.Pause,
            Escape = ConsoleKey.Escape,
            Spacebar = ConsoleKey.Spacebar,
            PageUp = ConsoleKey.PageUp,
            PageDown = ConsoleKey.PageDown,
            End = ConsoleKey.End,
            Home = ConsoleKey.Home,
            LeftArrow = ConsoleKey.LeftArrow,
            RightArrow = ConsoleKey.RightArrow,
            Select = ConsoleKey.Select,
            Print = ConsoleKey.Print,
            Execute = ConsoleKey.Execute,
            PrintScreen = ConsoleKey.PrintScreen,
            Insert = ConsoleKey.Insert,
            Delete = ConsoleKey.Delete,
            Help = ConsoleKey.Help,
            D0 = ConsoleKey.D0,
            D1 = ConsoleKey.D1,
            D2 = ConsoleKey.D2,
            D3 = ConsoleKey.D3,
            D4 = ConsoleKey.D4,
            D5 = ConsoleKey.D5,
            D6 = ConsoleKey.D6,
            D7 = ConsoleKey.D7,
            D8 = ConsoleKey.D8,
            D9 = ConsoleKey.D9,
            A = ConsoleKey.A,
            B = ConsoleKey.B,
            C = ConsoleKey.C,
            D = ConsoleKey.D,
            E = ConsoleKey.E,
            F = ConsoleKey.F,
            G = ConsoleKey.G,
            H = ConsoleKey.H,
            I = ConsoleKey.I,
            J = ConsoleKey.J,
            K = ConsoleKey.K,
            L = ConsoleKey.L,
            M = ConsoleKey.M,
            N = ConsoleKey.N,
            O = ConsoleKey.O,
            P = ConsoleKey.P,
            Q = ConsoleKey.Q,
            R = ConsoleKey.R,
            S = ConsoleKey.S,
            T = ConsoleKey.T,
            U = ConsoleKey.U,
            V = ConsoleKey.V,
            W = ConsoleKey.W,
            X = ConsoleKey.X,
            Y = ConsoleKey.Y,
            Z = ConsoleKey.Z,
            LeftWindows = ConsoleKey.LeftWindows,
            RightWindows = ConsoleKey.RightWindows,
            Applications = ConsoleKey.Applications,
            Sleep = ConsoleKey.Sleep,
            NumPad0 = ConsoleKey.NumPad0,
            NumPad1 = ConsoleKey.NumPad1,
            NumPad2 = ConsoleKey.NumPad2,
            NumPad3 = ConsoleKey.NumPad3,
            NumPad4 = ConsoleKey.NumPad4,
            NumPad5 = ConsoleKey.NumPad5,
            NumPad6 = ConsoleKey.NumPad6,
            NumPad7 = ConsoleKey.NumPad7,
            NumPad8 = ConsoleKey.NumPad8,
            NumPad9 = ConsoleKey.NumPad9,
            Multiply = ConsoleKey.Multiply,
            Add = ConsoleKey.Add,
            Separator = ConsoleKey.Separator,
            Subtract = ConsoleKey.Subtract,
            Decimal = ConsoleKey.Decimal,
            Divide = ConsoleKey.Divide,
            F1 = ConsoleKey.F1,
            F2 = ConsoleKey.F2,
            F3 = ConsoleKey.F3,
            F4 = ConsoleKey.F4,
            F5 = ConsoleKey.F5,
            F6 = ConsoleKey.F6,
            F7 = ConsoleKey.F7,
            F8 = ConsoleKey.F8,
            F9 = ConsoleKey.F9,
            F10 = ConsoleKey.F10,
            F11 = ConsoleKey.F11,
            F12 = ConsoleKey.F12,
            F13 = ConsoleKey.F13,
            F14 = ConsoleKey.F14,
            F15 = ConsoleKey.F15,
            F16 = ConsoleKey.F16,
            F17 = ConsoleKey.F17,
            F18 = ConsoleKey.F18,
            F19 = ConsoleKey.F19,
            F20 = ConsoleKey.F20,
            F21 = ConsoleKey.F21,
            F22 = ConsoleKey.F22,
            F23 = ConsoleKey.F23,
            F24 = ConsoleKey.F24,
            BrowserBack = ConsoleKey.BrowserBack,
            BrowserForward = ConsoleKey.BrowserForward,
            BrowserRefresh = ConsoleKey.BrowserRefresh,
            BrowserStop = ConsoleKey.BrowserStop,
            BrowserSearch = ConsoleKey.BrowserSearch,
            BrowserFavorites = ConsoleKey.BrowserFavorites,
            BrowserHome = ConsoleKey.BrowserHome,
            VolumeMute = ConsoleKey.VolumeMute,
            VolumeDown = ConsoleKey.VolumeDown,
            VolumeUp = ConsoleKey.VolumeUp,
            MediaNext = ConsoleKey.MediaNext,
            MediaPrevious = ConsoleKey.MediaPrevious,
            MediaStop = ConsoleKey.MediaStop,
            MediaPlay = ConsoleKey.MediaPlay,
            LaunchMail = ConsoleKey.LaunchMail,
            LaunchMediaSelect = ConsoleKey.LaunchMediaSelect,
            LaunchApp1 = ConsoleKey.LaunchApp1,
            LaunchApp2 = ConsoleKey.LaunchApp2,
            Oem1 = ConsoleKey.Oem1,
            OemPlus = ConsoleKey.OemPlus,
            OemComma = ConsoleKey.OemComma,
            OemMinus = ConsoleKey.OemMinus,
            OemPeriod = ConsoleKey.OemPeriod,
            Oem2 = ConsoleKey.Oem2,
            Oem3 = ConsoleKey.Oem3,
            Oem4 = ConsoleKey.Oem4,
            Oem5 = ConsoleKey.Oem5,
            Oem6 = ConsoleKey.Oem6,
            Oem7 = ConsoleKey.Oem7,
            Oem8 = ConsoleKey.Oem8,
            Oem102 = ConsoleKey.Oem102,
            Process = ConsoleKey.Process,
            Packet = ConsoleKey.Packet,
            Attention = ConsoleKey.Attention,
            CrSel = ConsoleKey.CrSel,
            ExSel = ConsoleKey.ExSel,
            EraseEndOfFile = ConsoleKey.EraseEndOfFile,
            Play = ConsoleKey.Play,
            Zoom = ConsoleKey.Zoom,
            NoName = ConsoleKey.NoName,
            Pa1 = ConsoleKey.Pa1,
            OemClear = ConsoleKey.OemClear
        }
        public HistoryUp HistoryUpKey { get; set; }
        public HistoryDown HistoryDownKey { get; set; }
        public bool ShowLoggingOutput { get; set; }
        
        [JsonIgnore]
        public Dictionary<string, object> ConfigStuff { get; private set; }
        public Settings(bool first, bool debug, string internalprefix, bool enforcePre, bool uniconver, int maxhist, HistoryUp upkey, HistoryDown downkey, bool showlog)
        {
            this.firstTime = first;
            this.debugMode = debug;
            this.internalCommandPrefix = internalprefix;
            this.enforcePrefix = enforcePre;
            this.unicodeConversion = uniconver;
            this.MaxHistoryLength = maxhist;
            this.HistoryUpKey = upkey;
            this.HistoryDownKey = downkey;
            this.ShowLoggingOutput = showlog;

            ConfigStuff = new Dictionary<string, object>
            {
                { "user.firstTime", this.firstTime },
                { "dev.debugMode", this.debugMode },
                { "core.internalCommandPrefix", this.internalCommandPrefix },
                { "core.enforcePrefix", this.enforcePrefix },
                { "core.unicodeConversion", this.unicodeConversion },
                { "core.ShowLoggingOutput", this.ShowLoggingOutput},
                { "cli.MaxHistoryLength", this.MaxHistoryLength },
                { "cli.HistoryUpKey", this.HistoryUpKey },
                { "cli.HistoryDownKey", this.HistoryDownKey }
            };
        }


        public static Exception UpdateSettings(string configPath)
        {
            try
            {
                string json = File.ReadAllText(configPath);
                Settings currentSettings = new Settings(true, false, "!", true, true, 100, HistoryUp.UpArrow, HistoryDown.DownArrow, false);

                JsonConvert.PopulateObject(json, currentSettings);
                File.WriteAllText(configPath, JsonConvert.SerializeObject(currentSettings, Formatting.Indented));
                return null;
            }
            catch (Exception ex)
            {
                return ex;
            }
        }
    }
}